"""
Django settings for LOGGING project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os, sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7_=2+#*-&)18@f=on&36mxyviiqj_a2ahm7h7w(1+&k(-%36p)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GlobalSettings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GlobalSettings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'



# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# If you want to use {{ MEDIA_URL }} in your templates,
# add 'django.template.context_processors.media' in the 'context_processors' option of TEMPLATES.
# Example: "http://media.example.com/"
MEDIA_URL = "/media/"


# The maximum size (in bytes) that an upload will be before it gets streamed to the file system.
# See Managing files for details.
FILE_UPLOAD_MAX_MEMORY_SIZE = 2.5 * 1024 * 1024

# The directory to store data to (typically files larger than FILE_UPLOAD_MAX_MEMORY_SIZE) temporarily while uploading files.
# If None, Django will use the standard temporary directory for the operating system. For example,
# this will default to /tmp on *nix-style operating systems.
FILE_UPLOAD_TEMP_DIR = None

# The name of the cookie to use for sessions. 
# This can be whatever you want (as long as it’s different from the other cookie names in your application).
#Default: 'sessionid'
SESSION_COOKIE_NAME = 'SID-LOGGING'

# The age of session cookies, in seconds.
# Default: 1209600 (2 weeks, in seconds)
SESSION_COOKIE_AGE = 86400



LOGS_ROOT = os.path.join(os.path.dirname(BASE_DIR), "logs.LOGGING")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'remote_verbose': {
            'format': '%(levelname)s %(asctime)s %(host)s %(module)s %(process)d %(processName)s %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        'null':{
            'format': ''
        },
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'toLocalFile' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.TimedRotatingFileHandler',
            'filename' : os.path.join(LOGS_ROOT, 'server.log'),
            'when' : 'D',
            'interval' : 1,
            'encoding' : 'utf-8',
            'formatter' : 'verbose',
        },
        'fromRemote' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.TimedRotatingFileHandler',
            'filename' : os.path.join(LOGS_ROOT, 'fromRemote.log'),
            'when' : 'D',
            'interval' : 1,
            'encoding' : 'utf-8',
            'formatter' : 'remote_verbose',
        },
    },
    'loggers': {
        'default': {
            'handlers': ["console", "toLocalFile"],
            'level': 'DEBUG',
            'propagate' : True,
        },
        'remote': {
            'handlers': ["console", "fromRemote"],
            'level': 'DEBUG',
            'propagate' : True,
        },
    }
}


SERVICE_PORT = 7100
